name: Throttler Microservices CI with ESO for secret mgmt
on:
  pull_request:
    branches: ['main','develop/*']
    types: [opened, synchronize, reopened]

# Both workflows should have the same concurrency group
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel any in-progress runs in the same group and runs only the latest commit

jobs:
  throttler-service-ci:
    uses: cloudhein/workflows/.github/workflows/common-jobs.yaml@68ad83ea0ce9d8d0c5a95fbe0cc0caae61e9c7c9
    with:
      working-directory: 'cmd/api'
      go-version: ">=1.22"
      binary-name: 'throttler' # This maps to -o throttler
      sonar-project-key: cloudhein_throttler
      sonar-organization: cloudhein
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  throttler-deploy-service:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    needs: throttler-service-ci
    uses: cloudhein/workflows/.github/workflows/deploy-jobs.yaml@68ad83ea0ce9d8d0c5a95fbe0cc0caae61e9c7c9
    with:
      service-name: 'throttler'
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      helm-repo: 'cloudhein/throttler-helm-chart'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
