name: Throttler Microservices CI with ESO for secret mgmt
on:
  pull_request:
    branches: ['main','develop/*']
    types: [opened, synchronize, reopened]

# Both workflows should have the same concurrency group
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel any in-progress runs in the same group and runs only the latest commit

jobs:
  throttler-service-ci:
    uses: cloudhein/workflows/.github/workflows/common-jobs.yaml@69fd4d876565d31d6f210426bde68feedf36d0d5
    with:
      working-directory: 'cmd/api'
      go-version: ">=1.22"
      binary-name: 'throttler' # This maps to -o throttler
      sonar-project-key: cloudhein_throttler
      sonar-organization: cloudhein
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  throttler-deploy-service:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.base_ref == 'main')
    needs: throttler-service-ci
    uses: cloudhein/workflows/.github/workflows/deploy-jobs.yaml@bd81baeea9abdc00bdac1b3cd5ce92d126833809
    with:
      service-name: 'throttler'
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      manifest-file: 'throttler.yaml'
      repository: 'cloudhein/flextrack-microservices'
      directory: 'flextrack-eks-cluster-eso'
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
